### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by cnlohr** [perigoso/sigrok-rvswd#2]
How do you actually apply this for use with sigrok/pulseview?

**Comment by cnlohr** [comment]
It looks like you have to install pulseview, install `libsigrokdecode` to your system (presumably to /usr/local/...), then copy the `sigrok-rvswd` folder to `/usr/local/share/libsigrokdecode/decoders`

**Comment by perigoso** [comment]
I honestly don't remember, and I can't find any resources on it quickly
What you wrote sounds about write, there is probably a way to do this locally, but I just don't remember, sorry :disappointed: 
When correctly installed it should just appear on pulseview like every other decoder

**Comment by perigoso** [comment]
Ah, I found it... see [Protocol_decoder_HOWTO](https://sigrok.org/wiki/Protocol_decoder_HOWTO)

Somewhere in there you have:

> You don't need to reinstall the whole [libsigrokdecode](https://sigrok.org/wiki/Libsigrokdecode) project every time you make a change on your decoder. Instead, you can use the environment variable SIGROKDECODE_DIR to point the software to your development directory:

> $ SIGROKDECODE_DIR=/path/to/libsigrokdecode/decoders/ sigrok-cli … -P <decodername>

**Comment by cnlohr** [comment]
I definitely don't want to have to worry about setting it.  Setting env vars to run a regular app the normal way is not a palatable way to live. 

I was able to install it once, and then it defaults to /usr/local/share/libsigrokdecode/decoders with the above instructions.

**Comment by perigoso** [comment]
Well, of course, I mentioned this because it is likely someone might want to tinker with this decoder, and modifying it locally makes sense then.
